### ISSUE TITLE
Add ability to run headless

### ISSUE THREAD

**Issue by dz4va** [corpusc/viscript#100]

**Comment by corpusc** [comment]
i started on this.  you can run headless at the moment, but it does practically nothing, as pretty much all the functionality comes from a Task/Terminal combo.  And takes input and gives output to glfw systems.

i suppose the next thing to do is to run a task outside of a terminal, which connects to dbus (with no need to subscribe to anything?).  and receives input from bufio instead of glfw events.  also have st.Print* output to the OS box only when in headless mode.
