### ISSUE TITLE
Cleanup, refactor extTask

### ISSUE THREAD

**Issue by dz4va** [corpusc/viscript#103]

**Comment by corpusc** [comment]
what kind of things did you have in mind to change?

**Comment by corpusc** [comment]
i think Red actually might have been copying from my TODO area that i was keeping in viscript.go before we started using JIRA or GitHub Issue system.  

and i renamed things such as "ExternalTask" extensively to "ExternalApp", since it wraps entire standalone apps, rather than just being a Task (which can be a fairly independent logic entity with no graphics or user input interface)

**Comment by corpusc** [comment]
since he clearly seems to have quit the project, and i see no immediate OTHER reason to refactor it, i'll close the issue.
